[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = "0xeaa56d1d155edd6a3ec5549c309cf46400177bbf13b31e604ca8b411720a7d2f"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]